#!/bin/bash

# simple watcher
# https://stackoverflow.com/questions/6475252/bash-script-watch-folder-execute-command

CMD=$1
ARGS=$2

daemon() {
    chsum1=""
    DIR=${CMD%/*}

    while [[ true ]]
    do
        chsum2=`find $DIR -type f -exec md5sum {} \; | sort -k 2 | md5sum`
        if [[ $chsum1 != $chsum2 ]] ; then
            echo -e "\n[watch] executing '$CMD $ARGS' ...\n"
            $CMD $ARGS
            chsum1=$chsum2
        fi
        sleep 2
    done
}

daemon
